#!/bin/sh

##Autostart

~/.config/polybar/launch.sh &
~/.fehbg
~/.config/bspwm/checkMonitor.sh &
run_dunst &
floating_noborder &
picom &
# Automount removable media
devmon &


focused=$(xrdb ~/.config/X11/xresources -query all | grep foreground | cut -f2)
normal=$(xrdb ~/.config/X11/xresources -query all | grep color8 | cut -f2)

bspc monitor DP1 -n center
bspc monitor eDP1 -n left

bspc monitor left -d 1 2 3 4 5 6
bspc monitor center -d 7 8 9

bspc config focused_border_color	"$focused"
bspc config normal_border_color		"$normal"
bspc config border_width		    3
bspc config window_gap 			    6
bspc config focus_follows_pointer	false
bspc config top_padding             40
bspc config split_ratio			    0.52
bspc config borderless_monocle		true
bspc config gapless_monocle		    false
bspc config single_monocle		    true

bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Nightly desktop='^2' follow=on
bspc rule -a mpv desktop='^5' state=fullscreen follow=on
bspc rule -a feh state=floating follow=on

